"""create email threads and emails

Revision ID: 454e73bbc032
Revises: 4951117db02c
Create Date: 2026-07-17 08:21:47.173491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '454e73bbc032'
down_revision: Union[str, Sequence[str], None] = '4951117db02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_threads',
    sa.Column('mail_account_id', sa.Uuid(), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=1024), nullable=False),
    sa.Column('normalized_subject', sa.String(length=500), nullable=True),
    sa.Column('current_thread_status', sa.Enum('UNCLASSIFIED', 'NEW_OUTREACH', 'WAITING_FOR_USER_REPLY', 'WAITING_FOR_RECRUITER_REPLY', 'INTERVIEW_SCHEDULING', 'INTERVIEW_CONFIRMED', 'ASSESSMENT_STAGE', 'REJECTED', 'OFFER_RECEIVED', 'CLOSED', 'NEEDS_REVIEW', name='thread_status', native_enum=False, create_constraint=True), server_default='UNCLASSIFIED', nullable=False),
    sa.Column('user_has_replied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latest_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_inbound_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_outbound_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('message_count >= 0', name=op.f('ck_email_threads_message_count_nonnegative')),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], name=op.f('fk_email_threads_mail_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_threads')),
    sa.UniqueConstraint('mail_account_id', 'provider_thread_id', name='uq_email_threads_account_provider_thread')
    )
    op.create_index('ix_email_threads_account_latest_message', 'email_threads', ['mail_account_id', 'latest_message_at'], unique=False)
    op.create_index('ix_email_threads_account_status', 'email_threads', ['mail_account_id', 'current_thread_status'], unique=False)
    op.create_table('emails',
    sa.Column('mail_account_id', sa.Uuid(), nullable=False),
    sa.Column('email_thread_id', sa.Uuid(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=1024), nullable=False),
    sa.Column('provider_immutable_id', sa.String(length=1024), nullable=True),
    sa.Column('internet_message_id', sa.String(length=998), nullable=True),
    sa.Column('provider_parent_folder_id', sa.String(length=1024), nullable=True),
    sa.Column('provider_change_key', sa.String(length=1024), nullable=True),
    sa.Column('web_link', sa.Text(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'UNKNOWN', name='email_direction', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('reply_to', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('to_recipients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cc_recipients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('bcc_recipients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.String(length=2048), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_attachments', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_provider_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('provider_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_thread_id'], ['email_threads.id'], name=op.f('fk_emails_email_thread_id_email_threads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], name=op.f('fk_emails_mail_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails')),
    sa.UniqueConstraint('mail_account_id', 'provider_immutable_id', name='uq_emails_account_provider_immutable'),
    sa.UniqueConstraint('mail_account_id', 'provider_message_id', name='uq_emails_account_provider_message')
    )
    op.create_index('ix_emails_account_deleted', 'emails', ['mail_account_id', 'is_provider_deleted'], unique=False)
    op.create_index('ix_emails_account_received_at', 'emails', ['mail_account_id', 'received_at'], unique=False)
    op.create_index('ix_emails_sender_email', 'emails', ['sender_email'], unique=False)
    op.create_index('ix_emails_thread_received_at', 'emails', ['email_thread_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emails_thread_received_at', table_name='emails')
    op.drop_index('ix_emails_sender_email', table_name='emails')
    op.drop_index('ix_emails_account_received_at', table_name='emails')
    op.drop_index('ix_emails_account_deleted', table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_email_threads_account_status', table_name='email_threads')
    op.drop_index('ix_email_threads_account_latest_message', table_name='email_threads')
    op.drop_table('email_threads')
    # ### end Alembic commands ###
