"""create users and mail accounts

Revision ID: 4951117db02c
Revises: 
Create Date: 2026-07-15 17:04:08.518244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4951117db02c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('primary_email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='user_status', native_enum=False, create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('primary_email', name=op.f('uq_users_primary_email'))
    )
    op.create_index('ix_users_status_created_at', 'users', ['status', 'created_at'], unique=False)
    op.create_table('mail_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('OUTLOOK', 'GMAIL', name='mailbox_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'REAUTH_REQUIRED', 'DISCONNECTED', name='mail_account_status', native_enum=False, create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mail_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_accounts')),
    sa.UniqueConstraint('user_id', 'provider', 'provider_subject', name='uq_mail_accounts_user_provider_subject')
    )
    op.create_index('ix_mail_accounts_provider_email', 'mail_accounts', ['provider', 'email_address'], unique=False)
    op.create_index('ix_mail_accounts_user_status', 'mail_accounts', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mail_accounts_user_status', table_name='mail_accounts')
    op.drop_index('ix_mail_accounts_provider_email', table_name='mail_accounts')
    op.drop_table('mail_accounts')
    op.drop_index('ix_users_status_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
