"""create classification tables

Revision ID: b68ef7e82e39
Revises: 454e73bbc032
Create Date: 2026-07-17 08:37:42.328657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b68ef7e82e39'
down_revision: Union[str, Sequence[str], None] = '454e73bbc032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_attempts',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('retry_of_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.Enum('ANTHROPIC', 'FALLBACK_RULES', 'USER_REVIEW', name='classification_origin', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('trigger', sa.Enum('EMAIL_INGESTION', 'RETRY', 'MANUAL_RECLASSIFICATION', 'BACKFILL', name='classification_trigger', native_enum=False, create_constraint=True), server_default='EMAIL_INGESTION', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_REVIEW', 'FAILED', name='classification_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), server_default='v1', nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response_text', sa.Text(), nullable=True),
    sa.Column('predicted_primary_category', sa.Enum('JOB_INTERVIEW', 'INTERVIEW_CONFIRMATION', 'REJECTION', 'APPLICATION_UPDATE', 'ASSESSMENT', 'OFFER', 'FOLLOW_UP_NEEDED', 'UNRECOGNIZED', 'NOT_JOB_RELATED', 'INITIAL_RECRUITER_OUTREACH', 'RECRUITER_FOLLOW_UP', name='email_category', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('predicted_secondary_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('predicted_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('was_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_source', sa.Enum('ANTHROPIC', 'MICROSOFT_GRAPH', 'GMAIL', 'INTERNAL', 'UNKNOWN', name='classification_error_source', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            predicted_confidence IS NULL\n            OR (\n                predicted_confidence >= 0\n                AND predicted_confidence <= 1\n            )\n            ', name=op.f('ck_classification_attempts_predicted_confidence_range')),
    sa.CheckConstraint('estimated_cost_usd IS NULL OR estimated_cost_usd >= 0', name=op.f('ck_classification_attempts_estimated_cost_nonnegative')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_classification_attempts_input_tokens_nonnegative')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_classification_attempts_latency_ms_nonnegative')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_classification_attempts_output_tokens_nonnegative')),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_classification_attempts_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_of_attempt_id'], ['classification_attempts.id'], name=op.f('fk_classification_attempts_retry_of_attempt_id_classification_attempts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_attempts')),
    sa.UniqueConstraint('origin', 'provider_request_id', name='uq_classification_attempts_origin_request_id')
    )
    op.create_index('ix_classification_attempts_email_created_at', 'classification_attempts', ['email_id', 'created_at'], unique=False)
    op.create_index('ix_classification_attempts_input_fingerprint', 'classification_attempts', ['input_fingerprint'], unique=False)
    op.create_index('ix_classification_attempts_origin_created_at', 'classification_attempts', ['origin', 'created_at'], unique=False)
    op.create_index('ix_classification_attempts_status_created_at', 'classification_attempts', ['status', 'created_at'], unique=False)
    op.create_table('email_classifications',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('source_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('primary_category', sa.Enum('JOB_INTERVIEW', 'INTERVIEW_CONFIRMATION', 'REJECTION', 'APPLICATION_UPDATE', 'ASSESSMENT', 'OFFER', 'FOLLOW_UP_NEEDED', 'UNRECOGNIZED', 'NOT_JOB_RELATED', 'INITIAL_RECRUITER_OUTREACH', 'RECRUITER_FOLLOW_UP', name='email_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('secondary_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('thread_status', sa.Enum('UNCLASSIFIED', 'NEW_OUTREACH', 'WAITING_FOR_USER_REPLY', 'WAITING_FOR_RECRUITER_REPLY', 'INTERVIEW_SCHEDULING', 'INTERVIEW_CONFIRMED', 'ASSESSMENT_STAGE', 'REJECTED', 'OFFER_RECEIVED', 'CLOSED', 'NEEDS_REVIEW', name='thread_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('review_status', sa.Enum('AUTO_CLASSIFIED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'USER_CORRECTED', name='review_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='email_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('classification_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_REVIEW', 'FAILED', name='classification_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('origin', sa.Enum('ANTHROPIC', 'FALLBACK_RULES', 'USER_REVIEW', name='classification_origin', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('action_needed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('should_surface', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('interview_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), server_default='v1', nullable=False),
    sa.Column('classification_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('error_source', sa.Enum('ANTHROPIC', 'MICROSOFT_GRAPH', 'GMAIL', 'INTERNAL', 'UNKNOWN', name='classification_error_source', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('classification_version > 0', name=op.f('ck_email_classifications_classification_version_positive')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_email_classifications_confidence_range')),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_email_classifications_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['classification_attempts.id'], name=op.f('fk_email_classifications_source_attempt_id_classification_attempts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_classifications')),
    sa.UniqueConstraint('email_id', name='uq_email_classifications_email'),
    sa.UniqueConstraint('source_attempt_id', name='uq_email_classifications_source_attempt')
    )
    op.create_index('ix_email_classifications_category_received', 'email_classifications', ['primary_category', 'classified_at'], unique=False)
    op.create_index('ix_email_classifications_processing_status', 'email_classifications', ['classification_status', 'classified_at'], unique=False)
    op.create_index('ix_email_classifications_review_status', 'email_classifications', ['review_status', 'classified_at'], unique=False)
    op.create_index('ix_email_classifications_surface_priority', 'email_classifications', ['should_surface', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_classifications_surface_priority', table_name='email_classifications')
    op.drop_index('ix_email_classifications_review_status', table_name='email_classifications')
    op.drop_index('ix_email_classifications_processing_status', table_name='email_classifications')
    op.drop_index('ix_email_classifications_category_received', table_name='email_classifications')
    op.drop_table('email_classifications')
    op.drop_index('ix_classification_attempts_status_created_at', table_name='classification_attempts')
    op.drop_index('ix_classification_attempts_origin_created_at', table_name='classification_attempts')
    op.drop_index('ix_classification_attempts_input_fingerprint', table_name='classification_attempts')
    op.drop_index('ix_classification_attempts_email_created_at', table_name='classification_attempts')
    op.drop_table('classification_attempts')
    # ### end Alembic commands ###
