from enum import StrEnum

class ThreadStatus(StrEnum):
    """Enum for thread statuses."""
    NEW_OUTREACH = "NEW_OUTREACH"
    WAITING_FOR_USER_REPLY = "WAITING_FOR_USER_REPLY"
    WAITING_FOR_RECRUITER_REPLY = "WAITING_FOR_RECRUITER_REPLY"
    INTERVIEW_SCHEDULING = "INTERVIEW_SCHEDULING"
    INTERVIEW_CONFIRMED = "INTERVIEW_CONFIRMED"
    ASSESSMENT_STAGE = "ASSESSMENT_STAGE"
    REJECTED = "REJECTED"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    CLOSED = "CLOSED"
    NEEDS_REVIEW = "NEEDS_REVIEW"